# Tomcat
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: common-server
          uri: lb://common-server
          predicates:
            - Path=/sys/common/**
