# Tomcat
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: common-service
          uri: lb://common-service/
          predicates:
            - Path=/sys/common/**
          filters:
            - StripPrefix=2
